#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/postedit/manage.py createinitialrevisions'"
python "$OPENSHIFT_REPO_DIR"wsgi/postedit/manage.py createinitialrevisions

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/postedit/manage.py schemamigration post_generator --auto'"
python "$OPENSHIFT_REPO_DIR"wsgi/postedit/manage.py schemamigration post_generator --initial

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/postedit/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/postedit/manage.py syncdb --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/postedit/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/postedit/manage.py migrate --noinput

